### ISSUE TITLE
Please add support for Hash, PartialEq, Eq, Debug

### ISSUE THREAD

**Issue by recesfulu** [dtolnay/dyn-clone#12]
Hash, PartialEq, Eq, Debug suffer from the same issue. It would be nice if we could have dyn-hash, dyn-partialeq, dyn-eq, dyn-debug and the corresponding macro for generating the impl for the boxed type like in dyn-cloneable.

**Comment by dtolnay** [comment]
I would prefer not to do it as part of this crate, but that would be a reasonable separate project.
