### ISSUE TITLE
Is there a reason for the `assert_eq!` in line 118?

### ISSUE THREAD

**Issue by jorgecarleitao** [dtolnay/dyn-clone#13]
I.e. under which conditions does this code panic?

**Comment by dtolnay** [comment]
https://github.com/dtolnay/dyn-clone/blob/07525737da610f4eb8008348e4d442a30af3bdf0/src/lib.rs#L118-L119

It's testing whether the data pointer part of a fat pointer comes before the metadata (vtable pointer, length, or whatever else).

It would fail if you have a fat pointer in which the data pointer does not come first.
