### ISSUE TITLE
clone box trait object with lifetime

### ISSUE THREAD

**Issue by ItsFunny** [dtolnay/dyn-clone#17]
The Trait is defined as  :
pub trait ChannelTrait<'e, 'a>
{
   async fn read_command(&mut self, suit: ContextWrapper<'a>);
}
Can you give me some advice about how to resolve this situation?

**Comment by dtolnay** [comment]
It works the same as documented in https://docs.rs/dyn-clone/1.0.6/dyn_clone/macro.clone_trait_object.html. There is an example involving a lifetime at https://github.com/dtolnay/dyn-clone/blob/1.0.6/tests/macros.rs#L50.
